## EMQX config for shutong
node {
  cookie = "ad74a4d4a3b6047e3bb07655216ddd91"
  data_dir = "/opt/emqx/data"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
}

dashboard {
  listeners.http {
    bind = "127.0.0.1:18083"
  }
  default_username = "admin"
  default_password = "public"
}

authentication = [
  {
    mechanism = password_based
    backend = built_in_database
    enable = true
  }
]

# bootstrap_users 已通过 add_emqx_users.sh 脚本创建
# emqx.conf 不支持此配置项
