## EMQX config for shutong
node {
  cookie = "ad74a4d4a3b6047e3bb07655216ddd91"
  data_dir = "/opt/emqx/data"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
}

dashboard {
  listeners.http {
    bind = "127.0.0.1:18083"
  }
  default_username = "admin"
  default_password = "public"
}

authentication = [
  {
    mechanism = password_based
    backend = built_in_database
    enable = true
  }
]

bootstrap_users = [
  {
    username = "sht_server"
    password = "8d22c8df90fd266b76327dfbe12837ef"
  },
  {
    username = "sht_device"
    password = "shutong-mqtt-2024"
  }
]
